config/routes.rb
Rails.application.routes.draw do
  get 'articles/new'
  get 'articles/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles
  root to: "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @article = Article.new
  end

  def index
    @articles = Article.all
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to articles_path
  end

  def edit
  end

  def update
    @article.update(article_params)
    redirect_to articles_path
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

# list, show, create, update and destroy

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= form_for @article do |f| %>
  <%= f.label :title, "Enter a title" %>
  <%= f.text_field :title %>

  <%= f.label :content, "Enter some content" %>
  <%= f.text_field :content %>

  <%= f.submit %>
<% end %>

app/views/articles/index.html.erb
<h1>Articles#index</h1>
<p>Find me in app/views/articles/index.html.erb</p>

<% @articles.each do |article| %>
<h3><%= article.title %>
  <%= link_to "[edit]", edit_article_path(article) %>
  <%= link_to "[delete]", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"} %></h3>
<p><%= article.content %></p>
<% end %>

<%= link_to "Create new article", articles_new_path %>

app/views/articles/new.html.erb
<h1>Create New Article</h1>

<%= form_for @article do |f| %>
  <%= f.label :title, "Enter a title" %>
  <%= f.text_field :title %>

  <%= f.label :content, "Enter some content" %>
  <%= f.text_field :content %>

  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>